name: clean-and-update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: null
  issue_comment:

jobs:
  relock:
    name: relock
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: relock
        uses: beckermr/relock-conda@7dd1c7ebd71d3389ba3dad4864b9fb6c2208a1d9
        with:
          github-token: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}
          automerge: true
          skip-if-pr-exists: true
          include-only-packages:
            anaconda-client
            conda-smithy
            conda
            conda-build
            conda-libmamba-solver
            mamba
            conda-forge-tick
            conda-forge-feedstock-ops
            conda-recipe-manager
            conda-souschef
            rattler-build
            rattler-build-conda-compat

  clean-and-cache:
    name: clean-and-cache
    runs-on: "ubuntu-latest"
    if: github.event_name != 'issue_comment'
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup conda
        uses: mamba-org/setup-micromamba@068f1ab4b37ed9b3d9f73da7db90a0cda0a48d29 # v1
        with:
          environment-file: conda-lock.yml
          environment-name: webservices
          condarc: |
            show_channel_urls: true
            channel_priority: strict
            channels:
              - conda-forge

      - name: generate token
        id: generate_token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        with:
          app-id: ${{ secrets.CF_CURATOR_APP_ID }}
          private-key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: install code
        run: |
          git config --global user.email "79913779+conda-forge-curator[bot]@users.noreply.github.com"
          git config --global user.name "conda-forge-curator[bot]"
          git config --global pull.rebase false
          mkdir -p ~/.conda-smithy/ && echo $GH_TOKEN > ~/.conda-smithy/github.token
          pip install --no-deps --no-build-isolation -e .
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: clean cf-staging
        run: |
          python scripts/clean_cf_staging.py
        env:
          STAGING_BINSTAR_TOKEN: ${{ secrets.HEROKU_ONLY_STAGING_BINSTAR_TOKEN }}

      - name: cache status data
        run: |
          cache-status-data
        env:
          CF_WEBSERVICES_APP_ID: ${{ secrets.CF_CURATOR_APP_ID }}
          CF_WEBSERVICES_PRIVATE_KEY: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}
